### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by Carioca-zz** [goosehub/landgrab#1]
We need a way to deal with spammers. Suggestions below:

**Comment by Carioca-zz** [comment]
- Rate limiting?
- Muting?
- Vote-kick?

**Comment by goosehub** [comment]
Do a query when user makes a new chat message, get all chat messages by that user in last minute. If more than x (probably 6), return false and do not add new row to chat table.

**Comment by Carioca-zz** [comment]
Short and simple, will do

**Comment by goosehub** [comment]
This was implemented long ago, closing this now.
