### ISSUE TITLE
Logging in not working

### ISSUE THREAD

**Issue by BritannicEgmo** [goosehub/landgrab#6]
**Hello, I have been having an issue on my local host of Landgrab, for some reason I can't login. Making accounts works fully with it making accounts in the database properly. Chat loads in fine, but logging into an account doesn't work. Any ideas on how to fix this? Thanks!**

**Comment by goosehub** [comment]
Oh wow. Don't usually check these github notifications so always feel free to email at goosepostbox@gmail.com.

Any errors in the network tab? What's your OS, PHP version, browser? Any clues when you var_dump in the relevant login methods? Let me know and I'll see what I can figure out!

**Comment by goosehub** [comment]
Closing as no response
